### ISSUE TITLE
Implement Vapourwave

### ISSUE THREAD

**Issue by universvm** [killiansheriff/LovelyPlots#8]
Hi, I was wondering whether you could integrate vapourwave as a style? 

https://github.com/dantaki/vapeplot

**Comment by universvm** [comment]
Hacking things together this is what it would look like: 

![Screenshot 2022-08-25 at 17 21 01](https://user-images.githubusercontent.com/17524568/186718029-5d036292-8802-4cee-a17a-d7c554c974aa.png)

**Comment by killiansheriff** [comment]
Sorry, totally missed this! Do you still want me to add it?
